spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: alex
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
  application:
    name: DEPARTMENT-SERVICE

server:
  port: 8090

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/