spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: alex
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update

server:
  port: 8080

department:
  service:
    url: http://localhost:8090/departments